@baseUrl = http://localhost:8080

POST {{baseUrl}}/login
Content-Type: application/json

{
    "nome": "admin",
    "senha": "123"
}

###
GET {{baseUrl}}/categorias/1


###
GET {{baseUrl}}/clientes
Authorization: Bearer 



