@baseUrl = http://localhost:8080

POST {{baseUrl}}/login
Content-Type: application/json

{
    "nome": "admin",
    "senha": "123"
}

###
GET {{baseUrl}}/categorias/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU5MzA1NDM1Mn0.wx6p77hAICJM71YGfaSah2cNFveTikHHLlbOVlJugyqK7NNrWQ55Z7PWB-VzGNoNf93FQQqtNH03JhCWs55M6A
