CREATE TABLE USUARIO (
	ID INT AUTO_INCREMENT,
	NOME VARCHAR(80),
	SENHA VARCHAR (1024),
	PRIMARY KEY(ID)
);

INSERT INTO USUARIO (NOME, SENHA) VALUES ('admin', '$2a$10$EUFZUU.49DnNeOWx9ZbuEubLuvlA0ggWrWSB.kSlpyrJc.5wBm/Rm');
INSERT INTO USUARIO (NOME, SENHA) VALUES ('padrao', '$2a$10$IA8v9WmHurHqpobNENaxOucggO5PtHQxaKcSMlzwZAck/xQWH/ftS');

CREATE TABLE PERFIS (
	USUARIO_ID INT,
	PERFIS INT
);

INSERT INTO PERFIS VALUES (1, 1);
INSERT INTO PERFIS VALUES (1, 0);
INSERT INTO PERFIS VALUES (2, 1);

CREATE TABLE CATEGORIA (
	ID INT AUTO_INCREMENT, 
	DESCRICAO VARCHAR(80),
	PRIMARY KEY(ID)
);

INSERT INTO CATEGORIA (DESCRICAO) VALUES ('Informática');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('Escritorio');
INSERT INTO CATEGORIA (DESCRICAO) VALUES ('Esporte');

CREATE TABLE PRODUTO (
	ID INT AUTO_INCREMENT, 
	CODIGO VARCHAR(4),
	DESCRICAO VARCHAR(80),
	PRECO DECIMAL(7, 2),
	CATEGORIA_ID INT,
	PRIMARY KEY(ID)
);

INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO, CATEGORIA_ID) VALUES ('0001', 'Computador HP G240', 2500.00, 1);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO, CATEGORIA_ID) VALUES ('0002', 'Dell XPS', 3500.00, 1);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO, CATEGORIA_ID) VALUES ('0003', 'Mesa escritório', 300.00, 2);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO, CATEGORIA_ID) VALUES ('0004', 'Bike Soul 29', 1700.00, 3);
INSERT INTO PRODUTO (CODIGO, DESCRICAO, PRECO, CATEGORIA_ID) VALUES ('0005', 'Bike Caloi 29', 16500.00, 3);

CREATE TABLE CLIENTE (
	ID INT AUTO_INCREMENT,
	NOME VARCHAR(480) NOT NULL,
	CPF VARCHAR(12) DEFAULT '',
	LOGRADOURO VARCHAR(480) DEFAULT '',
	NUMERO VARCHAR(10) DEFAULT '',
	BAIRRO VARCHAR(480) DEFAULT '',
	CRIADO_EM DATE,
	ATUALIZADO_EM DATE,
	PRIMARY KEY(ID)
);

INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Gabriel Eduardo', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Paulo Campos', '112860072', 'Rua 105', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Nair Campos', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Tereza dos Santos', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Elaine Giovanna', '38642299606', 'Rua Preta', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Yago dos Santos', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Giovanni dos Santos', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Valentina Priscila Ester', '', 'Rua 105', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Erick Matheus', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Matheus Fernandes', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Priscila Ester', '82978199148', 'Rua 105', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Pietra de Paula', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Sônia de Paula', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Raul Galvão', '33988593214', 'Rua 105', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Adriana Daiane Fabiana', '2020-08-15');
INSERT INTO CLIENTE (NOME, CRIADO_EM) VALUES ('Anderson Juan Manuel Galvão', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, CRIADO_EM) VALUES ('Laís Silva', '01255591862', 'Rua 105', '2020-08-15');
INSERT INTO CLIENTE (NOME, CPF, LOGRADOURO, NUMERO, BAIRRO, CRIADO_EM) 
VALUES ('Eliane Nicole Aragão', '54087598730', 'Rua 7', '156', 'Morada do Sol', '2020-08-15');

